language: python
python: 3.6

env:
  global:
    - DISPLAY=:99.0
    - MOZ_HEADLESS=1
    - WEB_HOST: http://127.0.0.1:7000

addons:
  chrome: stable

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "python -m http.server 7000 &"
  - sleep 4
  - pip install selenium==3.141.0

script: python tests/main_test.py

