language: python
dist: trusty

env:
  global:
    - DISPLAY=:99.0
    - WEB_HOST: http://127.0.0.1:7000

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  - ln --symbolic /usr/lib/chromium-browser/chromedriver "${HOME}/bin/chromedriver"
  - "sh -e /etc/init.d/xvfb start"
  - "python -m http.server 7000 &"
  - pip install selenium==3.141.0
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - sleep 5

script: python tests/main_test.py
