version: "2"
services:
  web:
    image: nginx:1.14.0-alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    ports:
      - "7009:80"
    container_name: glue_nginx

  python:
    build: ./tests/docker/build/python/.
    container_name: glue_python
    links:
      - selenium
    volumes:
      - ".:/opt/code:ro"
    environment:
      REMOTE_SELENIUM: selenium
      WEB_HOST: http://172.17.0.1:7009

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name: glue_chrome
    ports:
      - "0.0.0.0:4567:5900"
